server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:5001
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: 'Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/registration-api-process-manager.db
        output_dir: /tmp/

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: EOEPCA Registration API based on pygeoapi
        description: EOEPCA Registration API based on pygeoapi
        keywords:
            - EOEPCA
            - Earth observation
            - exploitation
            - processing
            - registration
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0
        url: https://eoepca.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0
    provider:
        name: EOEPCA
        url: https://eoepca.org
    contact:
        name: Tzotsos, Angelos
        position: Core Dev
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Greece
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:
    registrar:
        type: process
        processor:
            name: registration_api.processes.registration.RegistrarProcessor
